# Generated by Django 5.1.2 on 2025-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('religion', 'Religion'), ('history', 'History'), ('technology', 'Technology'), ('science', 'Science'), ('culture', 'Culture'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('other', 'Something else')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Enter a custom category if 'Something else' is selected", max_length=50, null=True),
        ),
    ]
